//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayitEkle
    {
        public int Id { get; set; }
        public Nullable<int> tc { get; set; }
        public string adSoyad { get; set; }
        public string yas { get; set; }
        public string cinsiyet { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string adres { get; set; }
    }
}
